<?php

namespace proof\app;
use proof\php\String;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-17 at 03:47:15.
 */
class ConfigurationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Configuration(new String('conftest.ini'));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\app\Configuration::getIterator
     */
    public function testIteration()
    {

        $count = NULL;

        foreach ($this->object as $value)
        {
            $count++;
        }

        $this->assertNotNull($count);

    }

    /**
     * @covers proof\app\Configuration::get
     */
    public function testGet()
    {

        $this->assertEquals("Big bertha", $this->object->get('name'));

        $this->assertInstanceOf("proof\util\Map", $this->object->get('version'));

    }

}
