<?php

namespace proof\sql;

use proof\php\String;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-03 at 04:33:26.
 */
class BasePDOConnectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BasePDOConnection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = \proof\helpers\ConnectionHelper::getBaseConnection();

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\sql\BasePDOConnection::connect
     */
    public function testConnect()
    {

        $this->assertTrue($this->object->connect());

    }

    /**
     * @covers proof\sql\BasePDOConnection::isConnected
     */
    public function testIsConnected()
    {

        $this->assertTrue($this->object->isConnected());

    }

    /**
     * @covers proof\sql\BasePDOConnection::disconnect
     */
    public function testDisconnect()
    {

        $this->assertNull($this->object->disconnect());

        $this->assertFalse($this->object->isConnected());

    }

    /**
     * @covers proof\sql\BasePDOConnection::create
     */
    public function testCreate()
    {

        $this->assertInstanceOf("proof\sql\Statement", $this->object->create(new String("Select * from users")));

    }

    /**
     * @covers proof\sql\BasePDOConnection::prepare
     */
    public function testPrepare()
    {

        $this->assertInstanceOf("proof\sql\PreparedStatement", $this->object->prepare(new String("Select * from users")));

    }

}
