<?php

namespace proof\sql;

use proof\php\String;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-03 at 04:03:42.
 */
class PreparedStatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PreparedStatement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $con = \proof\helpers\ConnectionHelper::getBaseConnection("proof", "proof-user", "test");

        $this->object = $con->prepare(new String($sql));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\sql\PreparedStatement::addParameter
     * @todo   Implement testAddParameter().
     */
    public function testAddParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\sql\PreparedStatement::addNamedParameter
     * @todo   Implement testAddNamedParameter().
     */
    public function testAddNamedParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\sql\PreparedStatement::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\sql\PreparedStatement::push
     * @todo   Implement testPush().
     */
    public function testPush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
