<?php

namespace proof\app;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-09 at 20:19:04.
 */
class UserAgentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UserAgent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserAgent;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers proof\app\UserAgent::request
     * 
     */
    public function testRequest()
    {

        $mock = $this->getMock("proof\net\http\HttpListener");

        $this->object->addListener($mock);

        $this->assertNull($this->object->request());

    }

}
