<?php
namespace tests;
/**
 * This file contains classes to aid with testing the  sql package.
 *
 */


class TestConnectorErrorHandler implements ConnectionErrorHandler
{

    /**
     * Used to respond to failed database connect attempts.
     */

    public function onError($message)
    {
        echo <<<TXT

This message is generated by the $class class. Connecting to the database seems to have failed
 with the message : <br/>:"$message"
TXT;
    }

}


?>
