<?php

namespace pelau\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-24 at 17:23:27.
 */
class ArrayListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ArrayList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayList;

    }

    /**
     * @covers \pelau\util\ArrayList::add
     */
    public function testAdd()
    {

        $obj = new \pelau\util\ArrayList;

        $this->assertInstanceOf('\pelau\util\ArrayList', $obj->add(1));

    }

    /**
     * @covers \pelau\util\ArrayList::remove
     */
    public function testRemove()
    {

        $obj = new ArrayList(['one'=>1]);

        $obj->remove('one');

        $this->assertNull($obj->get('one'));

    }

}
