<?php

namespace pelau\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-24 at 09:27:14.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \pelau\util\Collection
     */
    protected $emptyCol;

    /**
     * @var \pelau\util\Collection
     */
    protected $popuCol;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->emptyCol = $this->getMockForAbstractClass('\pelau\util\Collection');

        $this->popuCol = $this->getMockForAbstractClass
                ('\pelau\util\Collection', [[1, 2, 3, 'one' => 1, 'two' => 2, 'three' => 3]]);

    }

    /**
     * @covers \pelau\util\Collection::hasKey     .
     */
    public function testHasKey()
    {

        $this->assertFalse($this->emptyCol->hasKey('one'));

        $this->assertFalse($this->emptyCol->hasKey(1));

        $this->assertTrue($this->popuCol->hasKey('one'));

        $this->assertTrue($this->popuCol->hasKey(1));

    }

    /**
     * @covers \pelau\util\Collection::get
     */
    public function testGet()
    {

        $this->assertNull($this->assertNull($this->emptyCol->get(1)));

        $this->assertNull($this->assertNull($this->emptyCol->get('one')));

        $this->assertEquals(2, $this->popuCol->get(1));
        
        $this->assertEquals(1, $this->popuCol->get('one'));

    }

    /**
     * @covers \pelau\util\Collection::remove
     */
    public function testRemove()
    {

        $this->popuCol->remove('one');

        $this->assertNull($this->popuCol->get('one'));

    }


}
