<?php

namespace pelau\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-24 at 17:51:34.
 */
class MapTest extends \PHPUnit_Framework_TestCase
{


    /**
     * @covers \pelau\util\Map::set
     */
    public function testSet()
    {

        $map = new Map;

        $this->assertInstanceOf('\pelau\util\Map', $map->set('key', 'akey'));

    }

    /**
     * @covers pelau\util\Map::offsetSet
     * @covers pelau\util\Map::offsetExists
     * @covers pelau\util\Map::offsetGet
     * @covers pelau\util\Map::offsetUnset
     */
    public function testOffsetUsage()
    {

        $map = new Map;

        $this->assertNull($map['key']);

        $map['key'] = 'akey';

        $this->assertEquals('akey', $map['key']);




    }


}
