<?php

namespace pelau\sql;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-05 at 04:33:17.
 */
class PDOPreparedStatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PDOPreparedStatement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PDOPreparedStatement;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\sql\PDOPreparedStatement::bind
     * @todo   Implement testBind().
     */
    public function testBind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\PDOPreparedStatement::bindName
     * @todo   Implement testBindName().
     */
    public function testBindName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\PDOPreparedStatement::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\PDOPreparedStatement::push
     * @todo   Implement testPush().
     */
    public function testPush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\PDOPreparedStatement::addSQLEventListener
     * @todo   Implement testAddSQLEventListener().
     */
    public function testAddSQLEventListener()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
