<?php

namespace pelau\sql;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-07 at 00:53:33.
 */
use pelau\helpers\PDOHelper;
use pelau\php\String;

class PDOTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PDOTransaction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $con = PDOHelper::getPDO();

        $con->beginTransaction();

        $this->object = new PDOTransaction(new PDOSocket($con), $con);

    }


    /**
     * @covers pelau\sql\PDOTransaction::create
     */
    public function testCreate()
    {

        $this->assertInstanceOf("pelau\sql\Statement", $this->object->create(new String("Show tables")));

    }

    /**
     * @covers pelau\sql\PDOTransaction::prepare
     */
    public function testPrepare()
    {

        $this->assertInstanceOf("pelau\sql\PreparedStatement", $this->object->prepare(new String("Show tables")));
    }

    /**
     * @covers pelau\sql\PDOTransaction::commit
     */
    public function testCommit()
    {

        $this->assertTrue($this->object->commit());

    }

    /**
     * @covers pelau\sql\PDOTransaction::cancel
     */
    public function testCancel()
    {
        $this->assertTrue($this->object->cancel());
    }

}
