<?php

namespace proof\sql;


require_once dirname(__FILE__) . '/../../../proof/sql/Statement.php';

/**
 * Test class for Statement.
 * Generated by PHPUnit on 2012-08-04 at 12:28:56.
 */
class StatementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Statement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass(__NAMESPACE__ . '\\Statement');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\sql\Statement::attachStateHandler     .
     */
    public function testAttachStateListener()
    {
        $stub = $this->getMock('proof\sql\SQLStateListener');

        $this->assertInstanceOf(get_class($this->object), $this->object->attachStateListener($stub));

    }

}

?>
