<?php
namespace pelau\php;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-11 at 23:51:11.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if(!defined('OBJECT'))
            define('OBJECT', 'pelau\php\Object');
        $this->object = new Object;
    }

    /**
     * @covers pelau\php\Object::getClass
     */
    public function testGetClass()
    {

        $this->assertEquals(OBJECT, $this->object->getClass());

    }

    /**
     * @covers pelau\php\Object::__toString
     */
    public function test__toString()
    {
        $this->assertEquals(OBJECT, $this->object->__toString());
    }
}
