<?php

namespace proof\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:33:25.
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = new Event($this->getMock('proof\php\Object'));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\Event::getSource
     * @todo   Implement testGetSource().
     */
    public function testGetSource()
    {

        $this->assertInstanceOf('proof\php\Object', $this->object->getSource());

    }

    /**
     * @covers proof\util\Event::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        $test = "An event of type: proof\util\Event has occured.";
        $text = $this->object->getMessage();
        $text = (string)$text;
        $this->assertSame($test, $text);
    }

}
