<?php

namespace pelau\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-14 at 14:27:36.
 */
class IteratorAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var IteratorAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = new IteratorAdapter(new \ArrayIterator(array(0,1,2,3,4)), 5);

    }

    public function testIteration()
    {
        $count = -1;

        foreach($this->object as $key=>$value)
        {

            $count++;

            $this->assertEquals($count, $key);

            $this->assertEquals($key, $value);


        }

    }

    /**
     * @covers pelau\util\IteratorAdapter::hasNext
     * @covers pelau\util\IteratorAdapter::next
     */
    public function testNext()
    {
        $count = 0;

        while($this->object->hasNext())
        {

            $this->assertEquals($count, $this->object->next());

            $count++;


        }

        $this->assertEquals(5, $count);





    }

}
