<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../proof/util/Mock.php';

/**
 * Test class for Mock.
 * Generated by PHPUnit on 2012-08-09 at 20:15:11.
 */
class MockTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Mock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mock;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\Mock::getMock
     * @todo Implement testGetMock().
     */
    public function testGetMock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
