<?php

namespace proof\util;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-14 at 15:13:18.
 */
class PHPIteratorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PHPIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PHPIterator(array (1, 2, 3, 4));

    }

    public function testIteration()
    {
        $count = -1;

        foreach ($this->object as $key => $value)
        {

            $count++;

            $this->assertEquals($count, $key);

            $this->assertEquals($key, $value);
        }

    }

}
