<?php

namespace pelau\util;


require_once dirname(__FILE__) . '/../../../../pelau/util/Stack.php';

/**
 * Test class for Stack.
 * Generated by PHPUnit on 2012-07-25 at 11:55:34.
 */
class StackTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Stack
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Stack;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers pelau\util\Stack::push
     *
     */
    public function testPush()
    {

        $this->assertSame($this->object, $this->object->push(new \stdClass()));

    }

    /**
     * @covers pelau\util\Stack::pop
     * @expectedException pelau\util\StackEmptyException
     */
    public function testPopEmtpy()
    {

        $one = $this->object->pop();

    }

    public function testPushinAndPopin()
    {
        $this->object->push(new \stdClass());
        
        $this->assertEquals(1, $this->object->size());

        $this->object->pop();

        $this->assertEquals(0, $this->object->size());
    }

}

?>
