<?php

namespace pelau\app\web;
use pelau\php\String;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-24 at 13:44:55.
 */
class HtmlDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HtmlDocument
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HtmlDocument;

    }


    /**
     * @covers pelau\app\web\HtmlDocument::setCharacterSet
     * @todo   Implement testSetCharacterSet().
     */
    public function testSetCharacterSet()
    {

        $this->assertInstanceOf(get_class($this->object), $this->object->setCharacterSet(new String("UTF-8")));


    }

    /**
     * @covers pelau\app\web\HtmlDocument::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {

         $this->assertInstanceOf(get_class($this->object), $this->object->setTitle(new String("Test")));

    }

}
