<?php

namespace pelau\app\web;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-20 at 17:35:12.
 */
class WebPageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var WebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WebPage("test", "utf8");

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\app\web\WebPage::addContent
     * @todo   Implement testAddContent().
     */
    public function testAddContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\app\web\WebPage::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {

        

    }

}
