<?php

namespace pelau\app\web;

use pelau\php\String;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-15 at 05:11:08.
 */
class WebTemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var WebTemplate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WebTemplate(new String (getcwd()), new String ('title'), new String ('UTF-8'));

    }


    /**
     * @covers pelau\app\web\WebTemplate::render
     * @covers pelau\app\web\WebTemplate::put
     * @covers pelau\app\web\WebTemplate::put
     */
    public function testRender()
    {
        $this->assertInstanceOf(get_class($this->object), $this->object->add(new String('webtemplate.html')));
        $this->assertInstanceOf(get_class($this->object), $this->object->put('output', new String('<p>Hello World!</p>')));
        $this->assertNull($this->object->render());

    }


}
