<?php

namespace proof\net;
use proof\php\String;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-20 at 04:40:40.
 */
class UrlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Url(new String("http://example.com"));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\net\Url::getPath
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {

        $text = new String("http://example.com/this/is/an/example/with/7/levels");

        $url = new Url($text);

        $this->assertEquals("/this/is/an/example/with/7/levels", (string)$url->getPath());

    }

    /**
     * @covers proof\net\Url::getCleanPath
     * @todo   Implement testGetCleanPath().
     */
    public function testGetCleanPath()
    {

        $text = new String("http://example.com/this/is/an/example/with/7/levels");

        $url = new Url($text);

        $this->assertEquals(7, $url->getCleanPath()->size());

    }

    /**
     * @covers proof\net\Url::getHost
     * @todo   Implement testGetHost().
     */
    public function testGetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\net\Url::getProtocol
     * @todo   Implement testGetProtocol().
     */
    public function testGetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\net\Url::getPort
     * @todo   Implement testGetPort().
     */
    public function testGetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\net\Url::getQueryString
     * @todo   Implement testGetQueryString().
     */
    public function testGetQueryString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\net\Url::getFragment
     * @todo   Implement testGetFragment().
     */
    public function testGetFragment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\net\Url::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
