<?php

namespace proof\app;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-15 at 05:10:13.
 */
class VisitorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Visitor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Visitor;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\app\Visitor::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest()
    {

        $this->assertInstanceOf("proof\\net\http\HttpRequest", $this->object->getRequest());

    }

    /**
     * @covers proof\app\Visitor::visit
     */
    public function testVisit()
    {

        $_SERVER['REQUEST_METHOD'] = "POST";
        $this->object->attachHttpListener($this->getMockForAbstractClass("proof\\net\http\AbstractHttpListener"));
        $this->assertNull($this->object->visit());

    }

}
