<?php

namespace proof\php;


require_once dirname(__FILE__) . '/../../../proof/php/ImportList.php';

/**
 * Test class for ImportList.
 * Generated by PHPUnit on 2012-08-07 at 06:25:35.
 */
class ImportListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ImportList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImportList;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\php\ImportList::import
     * @todo Implement testImport().
     */
    public function testImport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
