<?php

namespace proof\web;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 19:11:01.
 */
class UserAgentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UserAgent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserAgent;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\web\UserAgent::addHttpListener
     * @todo   Implement testAddHttpListener().
     */
    public function testAddHttpListener()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\web\UserAgent::sendInput
     * @todo   Implement testSendInput().
     */
    public function testSendInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
