<?php

namespace pelau\net\http;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-12 at 10:30:00.
 */
class GetAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var GetAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GetAdapter;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\net\http\GetAdapter::onGet
     * @todo   Implement testOnGet().
     */
    public function testOnGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\net\http\GetAdapter::onPost
     * @todo   Implement testOnPost().
     */
    public function testOnPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
