<?php

namespace pelau\net\http;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-12 at 10:29:59.
 */
class GetEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var GetEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GetEvent;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}
