<?php

namespace pelau\net\http;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-12 at 10:29:58.
 */
class HeadersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Headers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Headers;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\net\http\Headers::headersSent
     * @todo   Implement testHeadersSent().
     */
    public function testHeadersSent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
