<?php

namespace pelau\net\http;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-04 at 04:09:12.
 */
class HttpHeaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HttpHeader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpHeader;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\net\http\HttpHeader::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
