<?php

namespace pelau\net\http;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-02-24 at 00:56:36.
 */
class HttpRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['REMOTE_ADDRESS'] = "127.0.0.1";
        $_SERVER['HTTP_USER_AGENT'] = "FireChrome";
        $this->object = new HttpRequest;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\net\http\HttpRequest::getProperty
     * @expectedException ErrorException
     */
    public function testGetProperty()
    {

        $this->assertEquals("127.0.0.1", $this->object->getProperty('REMOTE_ADDRESS'));
        $this->assertEquals("FireChrome", $this->object->getProperty('HTTP_USER_AGENT'));
        $this->assertNotEquals('Fish', $this->object->getProperty('FAV_FOOD'));

    }

}
