<?php

namespace proof\sql;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-06 at 22:57:34.
 */
use proof\helpers\PDOHelper;
use proof\php\String;

class PDOSocketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PDOSocket
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PDOSocket(PDOHelper::getPDO());

    }

    protected function tearDown()
    {

        $this->object->close();

    }

    /**
     * @covers proof\sql\PDOSocket::create
     */
    public function testCreate()
    {

        $this->assertInstanceOf("proof\sql\Statement", $this->object->create(new String("Show tables")));



    }

    /**
     * @covers proof\sql\PDOSocket::prepare
     */
    public function testPrepare()
    {

        $this->assertInstanceOf("proof\sql\PreparedStatement", $this->object->prepare(new String("SELECT * FROM users")));

    }

    /**
     * @covers proof\sql\PDOSocket::start
     * @todo   Implement testStart().
     */
    public function testStart()
    {

        $this->assertInstanceOf("proof\sql\Transaction", $this->object->start());

    }

}
