<?php

namespace pelau\sql;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-26 at 10:26:54.
 */
class SQLClauseAdapterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SQLClauseAdapter
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

      $array = array('select'=>'name,age,email', 'offset'=>'0,1', 'orderby'=>'age DESC');
      $this->obj = new SQLClauseAdapter(new \pelau\util\Map($array));

    }

    /**
     * @covers pelau\sql\SQLClauseAdapter::getSelect
     */
    public function testGetSelect()
    {


        $this->assertSame(" name,age,email", $this->obj->getSelect());

    }

    /**
     * @covers pelau\sql\SQLClauseAdapter::getOffset
     */
    public function testGetOffset()
    {

        $this->assertSame(' LIMIT 0,1', $this->obj->getOffset());

    }

    /**
     * @covers pelau\sql\SQLClauseAdapter::getOrderBy
     */
    public function testGetOrderBy()
    {

        $this->assertSame(' ORDER BY age DESC', $this->obj->getOrderBy());

    }

}
