<?php

namespace pelau\sql;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-01-26 at 10:25:17.
 */
class SQLDataSelectorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SQLDataSelector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SQLDataSelector;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers pelau\sql\SQLDataSelector::offset
     * @todo   Implement testOffset().
     */
    public function testOffset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\SQLDataSelector::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\SQLDataSelector::orderBy
     * @todo   Implement testOrderBy().
     */
    public function testOrderBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers pelau\sql\SQLDataSelector::toStatement
     * @todo   Implement testToStatement().
     */
    public function testToStatement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}
