<?php

namespace pelau\sql\pdo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-25 at 04:35:39.
 */
class PDOActiveTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PDOActive
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PDOActive;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers \pelau\sql\pdo\PDOActive::getClient
     */
    public function testGetClient()
    {

        $this->assertInstanceOf('\pelau\sql\pdo\PDOClient', $this->object->getClient());

    }

    /**
     * @covers \pelau\sql\pdo\PDOActive::prepare
     */
    public function testPrepare()
    {

        $sql =


        $this->assertInstanceOf('\pelau\sql\pdo\PDOPreparedStatement', $this->object->prepare($sql));

    }

    /**
     * @covers \pelau\sql\pdo\PDOActive::beginTransaction
     */
    public function testBeginTransaction()
    {

        $this->assertInstanceOf('\pelau\sql\pdo\PDOTransaction', $this->object->beginTransaction());

    }

}
