<?php

namespace pelau\sql\pdo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-26 at 04:22:11.
 */
class PDOClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers \pelau\sql\pdo\PDOClient::create
     */
    public function testCreate()
    {

        $client = new PDOClient(new \PDO("mysql:dname=test;host=127.0.0.1"));

        $this->assertInstanceOf('\pelau\sql\pdo\PDOStatement', $client->create('SELECT * FROM table'));

    }

    /**
     * @covers \pelau\sql\pdo\PDOClient::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare()
    {

        $client = new PDOClient(new \PDO("mysql:dname=test;host=127.0.0.1"));

        $this->assertInstanceOf('\pelau\sql\pdo\PDOPreparedStatement',
                $client->prepare('SELECT * FROM table'));

    }

}
