<?php

namespace pelau\sql\pdo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-25 at 21:22:40.
 */
class PDOConnectorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers \pelau\sql\pdo\PDOConnector::connect     .
     */
    public function testConnect()
    {

        $connector = new PDOConnector(
                        $this->getMock('\pelau\sql\pdo\PDOConnectionErrorHandler'));

        $this->assertInstanceOf('\pelau\sql\pdo\PDOConnection', $connector->connect("mysql:dname=test;host=127.0.0.1"));

    }

}
