<?php

namespace pelau\sql\pdo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-03-26 at 04:10:21.
 */
class PDOConnectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers \pelau\sql\pdo\PDOConnection::getClient
     */
    public function testGetClient()
    {

        $con = new PDOConnection(new \PDO("mysql:dname=test;host=127.0.0.1"));

        $this->assertInstanceOf('\pelau\sql\pdo\PDOClient', $con->getClient());

    }

    /**
     * @covers \pelau\sql\pdo\PDOConnection::getTransaction
     */
    public function testGetTransaction()
    {

        $con = new PDOConnection(new \PDO("mysql:dname=test;host=127.0.0.1"));

        $this->assertInstanceOf('\pelau\sql\pdo\PDOTransaction', $con->getTransaction());

    }

}
