<?php

namespace proof\app\web;

use proof\net\http\HttpRequest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-15 at 05:10:13.
 */
class VisitorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Visitor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Visitor(new HttpRequest);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\app\web\Visitor::getRemoteAddress()
     */
    public function getRemoteAddress()
    {

        $_SERVER['REMOTE_ADDR'] = "127.0.0.1";
         $this->assertEquals("localhost", $this->object->getRemoteAddress());

    }


    /**
     * @covers proof\app\web\Visitor::getURL
     */
    public function testgetURL()
    {
        $url = "http://www.example.com/example.php";
        $_SERVER['REQUEST_URI'] = $url;
        $this->assertEquals($url, (string)$this->object->getURL());


    }

    /**
     * @covers proof\app\web\Visitor::visit
     */
    public function testVisit()
    {

        $_SERVER['REQUEST_METHOD'] = "POST";
        $this->object->addHttpListener($this->getMockForAbstractClass("proof\\net\http\AbstractHttpListener"));
        $this->assertNull($this->object->visit());

    }

}
